### ISSUE TITLE
Not found outputPath

### ISSUE THREAD

**Issue by naz1719** [maciejmaciejewski/azure-pipelines-cucumber#36]
Can't find path
![image](https://user-images.githubusercontent.com/16464652/108845832-9359dd00-75e6-11eb-9ef5-9da2c2d3d877.png)
![image](https://user-images.githubusercontent.com/16464652/108845860-9ce34500-75e6-11eb-85e8-38755eff6f36.png)
![image](https://user-images.githubusercontent.com/16464652/108845910-aa003400-75e6-11eb-990e-19bf158a38b5.png)

**Comment by naz1719** [comment]
azure-pipelines.yml file:
```

jobs:
  # Build Electron
  - job: UserAcceptanceTest
    displayName: E2E-Tests
    pool:
      name: ado-win-pool
    timeoutInMinutes: 120
    steps:
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Build.SourcesDirectory)
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishPipelineArtifact@1
        displayName: 'Publishing build artifacts'
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)

      - task: NodeTool@0
        displayName: 'Install Node 12.x'
        inputs:
          versionSpec: 12.x

      - task: PublishCucumberReport@1
        displayName: 'Publish Cucumber Report'
        inputs:
          jsonDir: target/results/cucumber/
          outputPath: target/results/cucumber/
```
