### ISSUE TITLE
Unable to generate cucumber report on Azure DevOps by using Publish cucumber HTML report plugin

### ISSUE THREAD

**Issue by Madiha20** [maciejmaciejewski/azure-pipelines-cucumber#41]
Hi,

I am using Cucumber HTML reporter plugin for the first time and I am getting error in order to generate the Cucumber HTML report from Azure DevOps Pipeline. I have created a pipeline using maven and my Repo is also on Azure. Below is the pipeline detail;

I am not sure where exactly to add this? My project is Maven - Karate project.

```
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishCucumberReport@1
  inputs:
    jsonDir: './target/test-results/cucumber'
    outputPath: './target/cucumber-html-reports'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
    name: 'Cucumber HTML Report'
    title: 'MDS API Automation Results'

```
The error I am getting is valid as I don't have such file in target folder. Actually I have used .gitignore where I ignored loading of target folder into Repo.

As per the details in this plugin I have to do below; This extension reads Cucumber run report saved in JSON format. In order to get such file one needs to set up formater in Cucumber runner as following.

`--format=json:./results/cucumber.json`

![image](https://user-images.githubusercontent.com/88466826/131524601-99031dd7-4fec-4398-bbd8-b3ab50c3717f.png)

**Comment by sasyedkarim** [comment]
Hi @Madiha20  have the issue is resolved . I am also facing the same issue while publishing the cucumber report.

**Comment by Madiha20** [comment]
Hi @sasyedkarim ,

Yes, this was resolved for me. 

Please do one more task before the cucumber publisher and it will then publish the results.

```
# Copy the target folder to Azure Pipelines - Target folder contains the reports to be published
- task: CopyFiles@2
  condition: succeededOrFailed()
  inputs:
    Contents: 'target/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish build artifacts to Azure Pipelines 
- task: PublishPipelineArtifact@1
  condition: succeededOrFailed()
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'

# Publish Cucumber report to Azure Pipelines
- task: PublishCucumberReport@1
  inputs:
    jsonDir: '$(Build.ArtifactStagingDirectory)/target/karate-reports'
    outputPath: '$(Build.ArtifactStagingDirectory)'
    name: 'Test Results'

```
